language: node_js
sudo: false
dist: trusty
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost  
branches:
  only:
  - master
node_js:
  - '6'
script:
  - npm test